function data = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DATA = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  DATA = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  data = importfile("C:\Users\david\googledrive\MATLAB\soccer\real_deal\match_data1.csv", [2, 20000]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Apr-2020 19:45:19

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 20);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["PlayerId", "PlayerDisplayName", "SessionId", "Time", "ElapsedTime", "Speedms", "InstantaneousAccelerationImpulse", "HeartRateInterval", "Latitude", "Longitude", "AcclX", "AcclY", "AcclZ", "GyroX", "GyroY", "GyroZ", "Hacc", "Hdop", "QualityofSignal", "NoofSatellites"];
opts.VariableTypes = ["double", "categorical", "double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Time", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["PlayerDisplayName", "Time"], "EmptyFieldRule", "auto");

% Import the data
data = readtable(filename, opts);

end